services:
  mongodb:
    image: mongo:7
    container_name: adaptivelearnse-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  neo4j:
    image: neo4j:5
    container_name: adaptivelearnse-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/change-me-in-development
    volumes:
      - neo4j_data:/data

volumes:
  mongodb_data:
  neo4j_data:
